#ifndef INC_GLOBALS
#define INC_GLOBALS

#define BUFFER_SIZE 1024

#define MESSAGE_FIFO_FORMAT "/tmp/message_fifo_%d_to_%d"
#define MESSAGE_ACCEPTED_SIGNAL SIGUSR1
#define MESSAGE_REJECTED_SIGNAL SIGUSR2

#endif /* INC_GLOBALS */
